# Generated by Django 4.1 on 2022-08-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='test_score_of_general_ablity',
            new_name='test_score_of_general_ability',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='modified_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='更新时间'),
        ),
    ]
