# Generated by Django 4.1 on 2022-08-31 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_remove_candidate_first_interviewer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': [('export', 'Can export candidate list'), ('notify', 'notify interviewer for candidate reviewer')], 'verbose_name': '应聘者', 'verbose_name_plural': '应聘者'},
        ),
    ]
