# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=25, unique=True)),
                ('ipaddress01', models.CharField(max_length=16, unique=True)),
                ('ipaddress02', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('vip', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('remark', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'online'), (1, 'offline')])),
                ('log', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(verbose_name='Operate Time')),
                ('remark', models.CharField(blank=True, max_length=20, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('serverroom', models.CharField(max_length=10)),
                ('cabinet', models.CharField(max_length=10)),
                ('remark', models.CharField(blank=True, max_length=20, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Host')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'admin'), (1, 'guest')])),
                ('name', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('mail', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='operate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Position'),
        ),
        migrations.AddField(
            model_name='operate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
    ]
